[package]
name            = "lastfm-rs"
version         = "0.2.0"
authors         = ["Kamran Mackey <kamranm1200@gmail.com"]
license         = "MIT"
description     = "A Rust interface for Last.fm APIs"
repository      = "https://github.com/RoxasShadow/rustfm"
keywords        = ["lastfm"]
edition         = "2018"

[lib]
name            = "rustfm"
path            = "src/lib.rs"

[dependencies]
serde           = { version = "1.0", features = ["derive"] }
serde_json      = "1.0"
reqwest         = { version = "0.10", features = ["blocking", "json"] }
url             = "2.1"
tokio           = "0.2"
