[package]
name            = "lastfm-rs"
version         = "0.2.1"
authors         = ["Kamran Mackey <kamranm1200@gmail.com>"]
readme          = "README.md"
license         = "MIT"
description     = "A friendly interface for interacting with the Last.fm API."
repository      = "https://github.com/KamranMackey/lastfm-rs"
keywords        = ["lastfm", "web", "api"]
categories      = ["API bindings"]
edition         = "2018"

[lib]
name            = "rustfm"
path            = "src/lib.rs"

[dependencies]
serde           = { version = "1.0.104", features = ["derive"] }
serde_json      = "1.0.48"
reqwest         = { version = "0.10.1", features = ["blocking", "json"] }
url             = "2.1.1"
tokio           = "0.2.11"
